### ISSUE TITLE
missing the definitionh of  DEV_QUERY_RESULT_ACTION_DATA

### ISSUE THREAD

**Issue by Jcjroc** [Microsoft/NFC-Class-Extension-Driver#1]
Dear sir

 I am trying to make use of the following API and shall be most grateful if you could me a sample codes of the following APis for my reference:

 CFGMGR32.DLL:DevGetObjectProperties
 CFGMGR32.DLL:DevCreateObjectQuery

 as well as the structur eof tthe follwoing:
 DEV_QUERY_RESULT_ACTION_DATA

 Many thanks.

 Cheers.

 Jack

**Comment by marklan** [comment]
Hi Jack,

Those APIs are unfortunately internal-only to Microsoft. I assume you're talking about the NFC radio manager code (under "NfcRadioMedia"). The main purpose of this repository is so that people can build and make changes to the NFC class extension driver, which is under the "NfcCx" directory and uses code from the "libs" directory. The NFC radio manager code was added along with the NFC class extension driver code since it's somewhat related because it sends the radio management IOCTLs, but since some of the APIs that code uses are internal-only, there's no way to build it outside of Microsoft.

Thanks,
Mark
